### ISSUE TITLE
Does not compile on JDK9

### ISSUE THREAD

**Issue by AndreasKl** [rewe-digital/composer#11]
`java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at io.jsonwebtoken.impl.Base64Codec.encode(Base64Codec.java:21)
	at io.jsonwebtoken.impl.Base64UrlCodec.encode(Base64UrlCodec.java:22)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.base64UrlEncode(DefaultJwtBuilder.java:350)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.compact(DefaultJwtBuilder.java:296)
	at com.rewedigital.composer.session.CookieBasedSessionHandler.writeTo(CookieBasedSessionHandler.java:89)`

The jsonwebtoken implementation relies on JavaEE which is deprecated in Java9 and will be removed in Java10.

**Comment by AndreasKl** [comment]
Will be fixed in:
jjwt 0.10.0

**Comment by AndreasKl** [comment]
Fixed with #2  .

**Comment by thovid** [comment]
Closed via #15

**Comment by AndreasKl** [comment]
Fixed.
